# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_user(object):
    def setupUi(self, add_user):
        add_user.setObjectName("add_user")
        add_user.resize(330, 175)
        add_user.setMinimumSize(QtCore.QSize(330, 175))
        add_user.setMaximumSize(QtCore.QSize(330, 175))
        add_user.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        add_user.setAutoFillBackground(False)
        add_user.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        add_user.setModal(False)
        self.personData_gB = QtWidgets.QGroupBox(add_user)
        self.personData_gB.setGeometry(QtCore.QRect(10, 10, 311, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.personData_gB.setFont(font)
        self.personData_gB.setObjectName("personData_gB")
        self.personSurname_lE = QtWidgets.QLineEdit(self.personData_gB)
        self.personSurname_lE.setGeometry(QtCore.QRect(130, 70, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.personSurname_lE.setFont(font)
        self.personSurname_lE.setObjectName("personSurname_lE")
        self.personName_lE = QtWidgets.QLineEdit(self.personData_gB)
        self.personName_lE.setGeometry(QtCore.QRect(130, 30, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.personName_lE.setFont(font)
        self.personName_lE.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.personName_lE.setObjectName("personName_lE")
        self.personName_lbl = QtWidgets.QLabel(self.personData_gB)
        self.personName_lbl.setGeometry(QtCore.QRect(70, 30, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.personName_lbl.setFont(font)
        self.personName_lbl.setObjectName("personName_lbl")
        self.personSurname_lbl = QtWidgets.QLabel(self.personData_gB)
        self.personSurname_lbl.setGeometry(QtCore.QRect(40, 70, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.personSurname_lbl.setFont(font)
        self.personSurname_lbl.setObjectName("personSurname_lbl")
        self.addPerson_pB = QtWidgets.QPushButton(add_user)
        self.addPerson_pB.setGeometry(QtCore.QRect(90, 130, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.addPerson_pB.setFont(font)
        self.addPerson_pB.setStyleSheet("QPushButton {   \n"
"    background-color: rgb(170, 0, 0);    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.addPerson_pB.setObjectName("addPerson_pB")
        self.cancel_pB = QtWidgets.QPushButton(add_user)
        self.cancel_pB.setGeometry(QtCore.QRect(200, 130, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.cancel_pB.setFont(font)
        self.cancel_pB.setStyleSheet("QPushButton {   \n"
"    background-color: rgb(170, 0, 0);    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.cancel_pB.setObjectName("cancel_pB")

        self.retranslateUi(add_user)
        QtCore.QMetaObject.connectSlotsByName(add_user)

    def retranslateUi(self, add_user):
        _translate = QtCore.QCoreApplication.translate
        add_user.setWindowTitle(_translate("add_user", "Dialog"))
        self.personData_gB.setTitle(_translate("add_user", "Person\'s data"))
        self.personName_lbl.setText(_translate("add_user", "Name:"))
        self.personSurname_lbl.setText(_translate("add_user", "Surname:"))
        self.addPerson_pB.setText(_translate("add_user", "Add"))
        self.cancel_pB.setText(_translate("add_user", "Cancel"))
