# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'person_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_person_selection(object):
    def setupUi(self, person_selection):
        person_selection.setObjectName("person_selection")
        person_selection.resize(294, 380)
        person_selection.setMinimumSize(QtCore.QSize(294, 380))
        person_selection.setMaximumSize(QtCore.QSize(294, 380))
        person_selection.setStyleSheet("QDialog\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 0);    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.personsListGB = QtWidgets.QGroupBox(person_selection)
        self.personsListGB.setGeometry(QtCore.QRect(10, 10, 271, 311))
        self.personsListGB.setStyleSheet("QScrollBar:vertical \n"
"{\n"
"     background: black;;\n"
"     width: 17px;    \n"
"     margin: 0px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    background: rgb(170, 0, 0);\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"    margin: 2px;\n"
"    margin-left: 4px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"\n"
"    background: red;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical \n"
"{\n"
"     background: none;\n"
" }\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    background: none;\n"
" }\n"
" \n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"    background: none;\n"
" }\n"
"")
        self.personsListGB.setTitle("")
        self.personsListGB.setObjectName("personsListGB")
        self.persons_lbl = QtWidgets.QLabel(self.personsListGB)
        self.persons_lbl.setGeometry(QtCore.QRect(10, 10, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.persons_lbl.setFont(font)
        self.persons_lbl.setStyleSheet("QLabel\n"
"{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.persons_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.persons_lbl.setWordWrap(True)
        self.persons_lbl.setObjectName("persons_lbl")
        self.persons_lst = QtWidgets.QListWidget(self.personsListGB)
        self.persons_lst.setGeometry(QtCore.QRect(10, 61, 251, 231))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.persons_lst.setPalette(palette)
        self.persons_lst.setStyleSheet("QListWidget\n"
"{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.persons_lst.setObjectName("persons_lst")
        self.selectPerson_pB = QtWidgets.QPushButton(person_selection)
        self.selectPerson_pB.setGeometry(QtCore.QRect(40, 330, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.selectPerson_pB.setFont(font)
        self.selectPerson_pB.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.selectPerson_pB.setObjectName("selectPerson_pB")
        self.cancel_pB = QtWidgets.QPushButton(person_selection)
        self.cancel_pB.setGeometry(QtCore.QRect(160, 330, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.cancel_pB.setFont(font)
        self.cancel_pB.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.cancel_pB.setObjectName("cancel_pB")

        self.retranslateUi(person_selection)
        QtCore.QMetaObject.connectSlotsByName(person_selection)

    def retranslateUi(self, person_selection):
        _translate = QtCore.QCoreApplication.translate
        person_selection.setWindowTitle(_translate("person_selection", "Dialog"))
        self.persons_lbl.setText(_translate("person_selection", "Select person you want this fingerprint allign to:"))
        self.selectPerson_pB.setText(_translate("person_selection", "Select"))
        self.cancel_pB.setText(_translate("person_selection", "Cancel"))
